# NumPy

numpy's main object is called an ndarray.  It is:

1. multidimensional
2. homogenous
3. array

Meaning, it is a table elements, usually numbers.  All elements are the same type.  Elements are accessed by a tuple of positive integers.

Dimensions are called axes.
The number of axes is the rank.

In [1]:
import numpy as np

t = np.array([1,2,3])

print(t)

[1 2 3]


In [2]:
np.ndim(t)

1

In [5]:
a = np.array(np.arange(15).reshape(3,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
np.ndim(a)

2

In [7]:
a.shape

(3, 5)

In [8]:
a.ndim

2

In [9]:
a.dtype.name

'int64'

In [10]:
#size in bites
a.itemsize

8

In [11]:
a.size

15

In [12]:
type(a)

numpy.ndarray

We have three ways to access "row" 1 of a

In [13]:
a[1]

array([5, 6, 7, 8, 9])

In [14]:
a[1,]

array([5, 6, 7, 8, 9])

In [15]:
a[1,:]

array([5, 6, 7, 8, 9])

To get column in postiion 2:

In [16]:
a[:,2]

array([ 2,  7, 12])

To get a single element in "row" 0, "column" 2

In [17]:
a[0,2]

2

Creating and modifying an array:

In [18]:
c = np.array([2,3,4])
c.dtype.name

'int64'

In [19]:
d = np.array([1.2,2.3,3.4])
d.dtype.name
              

'float64'

Let's change one element of c:

In [20]:
c[1] = 4.5
c.dtype.name

'int64'

Note that the type didn't change

In [21]:
print(c)

[2 4 4]


The value was added but was converted to an int64 - be careful - type matters!

NumPy interprets a sequence of sequences as a 2D array.  A sequence of sequence of sequences as a 3D array - etc

In [23]:
g = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Remember c from above?  Here is how we can change from integers to floats:

In [24]:
print(c)
c = np.array(c, dtype = float)
print(c)
c[1] = 4.5
print(c)

[2 4 4]
[2. 4. 4.]
[2.  4.5 4. ]


Suppose you want to fill an array with all zeros or 1 (this is a suprisingly common task in data science)

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Similar to the range funtion in the standard python library NumPy has arange.  It allows us to create an array containing a range of numbers evenly spaced.

In [30]:
np.arange(10,30,2) #start, stop, step

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [29]:
np.arange(0.3, 1.5, 0.1)

array([0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3, 1.4])

Exercise 1: Create a 4X2 integer array and prints its attributes
* The shape of an array.
* Array dimensions.
* The Length of each element of the array in bytes.

Save your code and output as a screenshot named numpy1.jpeg




In [ ]:
# Cell for coding exercise 1

Exercise 2: Following is the given numpy array return array of odd rows and even columns.  Save your code and output as a screenshot named numpy2.jpeg

In [ ]:

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

# Your code here